package com.example.llmhost

data class HuggingFaceModelEntry(
    val id: String,
    val name: String,
    val repoId: String,
    val fileName: String,
    val expectedBytes: Long,
    val expectedSha256: String? = null,
    val license: String,
    val parameters: String,
    val quantization: String,
    val notes: String,
) {
    val revision: String = "main"
    val downloadUrl: String
        get() = "https://huggingface.co/$repoId/resolve/$revision/$fileName"
    val apiUrl: String
        get() = "https://huggingface.co/api/models/$repoId?blobs=true"
    val rawPointerUrl: String
        get() = "https://huggingface.co/$repoId/raw/$revision/$fileName"
}

sealed class ModelDownloadState {
    data object Idle : ModelDownloadState()
    data class Running(
        val entry: HuggingFaceModelEntry,
        val stage: Stage,
        val bytesDone: Long,
        val totalBytes: Long?,
        val message: String? = null,
    ) : ModelDownloadState() {
        enum class Stage {
            QUEUED,
            VERIFYING_METADATA,
            DOWNLOADING,
            VERIFYING_FILE,
            IMPORTING,
        }
    }
    data class Success(val modelId: String, val entryName: String) : ModelDownloadState()
    data class Failure(val entryName: String, val message: String) : ModelDownloadState()
    data object Cancelled : ModelDownloadState()
}

object HuggingFaceModelCatalog {
    val entries: List<HuggingFaceModelEntry> = listOf(
        HuggingFaceModelEntry(
            id = "qwen25_05b_q4km",
            name = "Qwen2.5 0.5B Instruct",
            repoId = "Qwen/Qwen2.5-0.5B-Instruct-GGUF",
            fileName = "qwen2.5-0.5b-instruct-q4_k_m.gguf",
            expectedBytes = 491L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "0.5B",
            quantization = "Q4_K_M",
            notes = "Small text/chat model; best first candidate for phone CPU testing.",
        ),
        HuggingFaceModelEntry(
            id = "qwen25_15b_q4km",
            name = "Qwen2.5 1.5B Instruct",
            repoId = "Qwen/Qwen2.5-1.5B-Instruct-GGUF",
            fileName = "qwen2.5-1.5b-instruct-q4_k_m.gguf",
            expectedBytes = 1_120L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "1.5B",
            quantization = "Q4_K_M",
            notes = "Better quality than 0.5B while still much smaller than 4B VL models.",
        ),
        HuggingFaceModelEntry(
            id = "qwen25_coder_05b_q4km",
            name = "Qwen2.5 Coder 0.5B",
            repoId = "Qwen/Qwen2.5-Coder-0.5B-Instruct-GGUF",
            fileName = "qwen2.5-coder-0.5b-instruct-q4_k_m.gguf",
            expectedBytes = 491L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "0.5B",
            quantization = "Q4_K_M",
            notes = "Tiny text/code model for fast coding-focused benchmark comparisons.",
        ),
        HuggingFaceModelEntry(
            id = "smollm2_360m_q4km",
            name = "SmolLM2 360M Instruct",
            repoId = "QuantFactory/SmolLM2-360M-Instruct-GGUF",
            fileName = "SmolLM2-360M-Instruct.Q4_K_M.gguf",
            expectedBytes = 271L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "360M",
            quantization = "Q4_K_M",
            notes = "Very small Apache-licensed chat model; good for quick sanity and latency baselines.",
        ),
        HuggingFaceModelEntry(
            id = "lfm2_350m_q4km",
            name = "LFM2 350M",
            repoId = "LiquidAI/LFM2-350M-GGUF",
            fileName = "LFM2-350M-Q4_K_M.gguf",
            expectedBytes = 229L * 1024L * 1024L,
            expectedSha256 = "a4d000c7064bd3b2e42c6845836286a899a4e79cf1791da1a6797b58d575957d",
            license = "LFM1.0",
            parameters = "350M",
            quantization = "Q4_K_M",
            notes = "Tiny edge-focused model; useful to test whether the app is hardware-bound or model-bound.",
        ),
        HuggingFaceModelEntry(
            id = "llama32_1b_q4km",
            name = "Llama 3.2 1B Instruct",
            repoId = "bartowski/Llama-3.2-1B-Instruct-GGUF",
            fileName = "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
            expectedBytes = 808L * 1024L * 1024L,
            license = "Llama 3.2 Community",
            parameters = "1B",
            quantization = "Q4_K_M",
            notes = "Popular small instruct baseline; license is open-weight, not Apache/MIT style.",
        ),
        HuggingFaceModelEntry(
            id = "gemma3_1b_q4km",
            name = "Gemma 3 1B IT",
            repoId = "ggml-org/gemma-3-1b-it-GGUF",
            fileName = "gemma-3-1b-it-Q4_K_M.gguf",
            expectedBytes = 806_058_240L,
            expectedSha256 = "8ccc5cd1f1b3602548715ae25a66ed73fd5dc68a210412eea643eb20eb75a135",
            license = "Gemma terms",
            parameters = "1B",
            quantization = "Q4_K_M",
            notes = "Useful Gemma-family baseline; license requires review before redistribution.",
        ),
        // --- Expanded catalog: more sizes, architectures, and quants ---
        HuggingFaceModelEntry(
            id = "phi3_mini_38b_q4km",
            name = "Phi-3-mini 3.8B Instruct",
            repoId = "bartowski/Phi-3-mini-4k-instruct-GGUF",
            fileName = "Phi-3-mini-4k-instruct-Q4_K_M.gguf",
            expectedBytes = 2_300L * 1024L * 1024L,
            license = "MIT",
            parameters = "3.8B",
            quantization = "Q4_K_M",
            notes = "Microsoft Phi-3-mini; strong reasoning for its size, MIT license.",
        ),
        HuggingFaceModelEntry(
            id = "phi4_mini_38b_q4km",
            name = "Phi-4-mini 3.8B Instruct",
            repoId = "bartowski/Phi-4-mini-instruct-GGUF",
            fileName = "Phi-4-mini-instruct-Q4_K_M.gguf",
            expectedBytes = 2_300L * 1024L * 1024L,
            license = "MIT",
            parameters = "3.8B",
            quantization = "Q4_K_M",
            notes = "Microsoft Phi-4-mini; improved reasoning over Phi-3, MIT license.",
        ),
        HuggingFaceModelEntry(
            id = "llama32_3b_q4km",
            name = "Llama 3.2 3B Instruct",
            repoId = "bartowski/Llama-3.2-3B-Instruct-GGUF",
            fileName = "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
            expectedBytes = 2_020L * 1024L * 1024L,
            license = "Llama 3.2 Community",
            parameters = "3B",
            quantization = "Q4_K_M",
            notes = "Meta Llama 3.2 3B; strong general-purpose instruct model with long-context support.",
        ),
        HuggingFaceModelEntry(
            id = "gemma3_4b_q4km",
            name = "Gemma 3 4B IT",
            repoId = "ggml-org/gemma-3-4b-it-GGUF",
            fileName = "gemma-3-4b-it-Q4_K_M.gguf",
            expectedBytes = 2_620L * 1024L * 1024L,
            license = "Gemma terms",
            parameters = "4B",
            quantization = "Q4_K_M",
            notes = "Google Gemma 3 4B; strong for its size, good multilingual support.",
        ),
        HuggingFaceModelEntry(
            id = "qwen25_3b_q4km",
            name = "Qwen2.5 3B Instruct",
            repoId = "bartowski/Qwen2.5-3B-Instruct-GGUF",
            fileName = "Qwen2.5-3B-Instruct-Q4_K_M.gguf",
            expectedBytes = 1_940L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "3B",
            quantization = "Q4_K_M",
            notes = "Alibaba Qwen2.5 3B; excellent coding and reasoning for its size, Apache-2.0.",
        ),
        HuggingFaceModelEntry(
            id = "qwen25_7b_iq3xxs",
            name = "Qwen2.5 7B Instruct",
            repoId = "bartowski/Qwen2.5-7B-Instruct-GGUF",
            fileName = "Qwen2.5-7B-Instruct-IQ3_XXS.gguf",
            expectedBytes = 3_240L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "7B",
            quantization = "IQ3_XXS",
            notes = "Qwen2.5 7B with aggressive IQ3_XXS quant; fits flagship phones with >8 GiB RAM.",
        ),
        HuggingFaceModelEntry(
            id = "deepseek_r1_distill_qwen_15b_q4km",
            name = "DeepSeek-R1-Distill-Qwen 1.5B",
            repoId = "bartowski/DeepSeek-R1-Distill-Qwen-1.5B-GGUF",
            fileName = "DeepSeek-R1-Distill-Qwen-1.5B-Q4_K_M.gguf",
            expectedBytes = 1_060L * 1024L * 1024L,
            license = "MIT",
            parameters = "1.5B",
            quantization = "Q4_K_M",
            notes = "DeepSeek-R1 distilled reasoning model; chain-of-thought reasoning in a small package.",
        ),
        HuggingFaceModelEntry(
            id = "granite31_2b_q4km",
            name = "Granite 3.1 2B Instruct",
            repoId = "bartowski/granite-3.1-2b-instruct-GGUF",
            fileName = "granite-3.1-2b-instruct-Q4_K_M.gguf",
            expectedBytes = 1_490L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "2B",
            quantization = "Q4_K_M",
            notes = "IBM Granite 3.1 2B; solid enterprise-friendly model, Apache-2.0.",
        ),
        HuggingFaceModelEntry(
            id = "granite31_3b_q4km",
            name = "Granite 3.1 3B Instruct",
            repoId = "bartowski/granite-3.1-3b-a800m-instruct-GGUF",
            fileName = "granite-3.1-3b-a800m-instruct-Q4_K_M.gguf",
            expectedBytes = 2_010L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "3B",
            quantization = "Q4_K_M",
            notes = "IBM Granite 3.1 3B MoE; mixture-of-experts for efficient inference.",
        ),
        HuggingFaceModelEntry(
            id = "ministral_3b_q4km",
            name = "Ministral 3B Instruct",
            repoId = "bartowski/Ministral-3B-instruct-GGUF",
            fileName = "Ministral-3B-instruct-Q4_K_M.gguf",
            expectedBytes = 2_050L * 1024L * 1024L,
            license = "Mistral Research License",
            parameters = "3B",
            quantization = "Q4_K_M",
            notes = "Mistral Ministral 3B; efficient edge-focused model from Mistral AI.",
        ),
        HuggingFaceModelEntry(
            id = "tinyllama_11b_q4km",
            name = "TinyLlama 1.1B Chat",
            repoId = "TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
            fileName = "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
            expectedBytes = 700L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "1.1B",
            quantization = "Q4_K_M",
            notes = "TinyLlama 1.1B; very fast on weak hardware, good for quick answers.",
        ),
        HuggingFaceModelEntry(
            id = "stablelm_zephyr_3b_q4km",
            name = "StableLM Zephyr 3B",
            repoId = "bartowski/stablelm-zephyr-3b-GGUF",
            fileName = "stablelm-zephyr-3b-Q4_K_M.gguf",
            expectedBytes = 1_870L * 1024L * 1024L,
            license = "CC-BY-NC-SA-4.0",
            parameters = "3B",
            quantization = "Q4_K_M",
            notes = "Stability AI StableLM Zephyr 3B; tuned for helpfulness, non-commercial license.",
        ),
        HuggingFaceModelEntry(
            id = "qwen25_05b_iq2xxs",
            name = "Qwen2.5 0.5B Instruct (compact)",
            repoId = "bartowski/Qwen2.5-0.5B-Instruct-GGUF",
            fileName = "qwen2.5-0.5b-instruct-IQ2_XXS.gguf",
            expectedBytes = 189L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "0.5B",
            quantization = "IQ2_XXS",
            notes = "Ultra-compact Qwen2.5 0.5B; under 200 MiB, fits any device.",
        ),
        HuggingFaceModelEntry(
            id = "qwen25_15b_iq3xxs",
            name = "Qwen2.5 1.5B Instruct (compact)",
            repoId = "bartowski/Qwen2.5-1.5B-Instruct-GGUF",
            fileName = "qwen2.5-1.5b-instruct-IQ3_XXS.gguf",
            expectedBytes = 550L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "1.5B",
            quantization = "IQ3_XXS",
            notes = "Compact Qwen2.5 1.5B; ~550 MiB with IQ3_XXS, good quality/size tradeoff.",
        ),
        HuggingFaceModelEntry(
            id = "smollm2_17b_q4km",
            name = "SmolLM2 1.7B Instruct",
            repoId = "QuantFactory/SmolLM2-1.7B-Instruct-GGUF",
            fileName = "SmolLM2-1.7B-Instruct.Q4_K_M.gguf",
            expectedBytes = 1_110L * 1024L * 1024L,
            license = "Apache-2.0",
            parameters = "1.7B",
            quantization = "Q4_K_M",
            notes = "HuggingFace SmolLM2 1.7B; strong Apache-2.0 model between 360M and 1.5B sizes.",
        ),
    )

    fun find(id: String): HuggingFaceModelEntry? = entries.firstOrNull { it.id == id }
}
