#!/usr/bin/env bash
#
# capture-baseline.sh - emit the deterministic inference baseline manifest.
#
# The manifest is the PIR-00 provenance freeze: it records the source-derived
# identities (HEAD, llama.cpp gitlink, local patch, build inputs) and the host
# toolchain that produced them. It intentionally contains NO model, device or
# measured-benchmark provenance; those belong to a later on-device run record.
#
# Default is a DRY RUN: the JSON is printed to stdout and nothing is written.
#
# Usage:
#   scripts/inference/capture-baseline.sh                 # dry run -> stdout
#   scripts/inference/capture-baseline.sh --apply         # write the manifest
#   scripts/inference/capture-baseline.sh --out PATH --apply
#
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)"
cd "$ROOT"

OUT="research/inference/baseline.lock.json"
APPLY=0

usage() {
  sed -n '3,14p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

while (($#)); do
  case "$1" in
    --apply) APPLY=1; shift ;;
    --out) OUT="${2:?--out requires a path}"; shift 2 ;;
    --out=*) OUT="${1#--out=}"; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "capture-baseline: unknown argument: $1" >&2; exit 2 ;;
  esac
done

# --- capture helpers ---------------------------------------------------------

# sha256 digest of a file (empty string if the file is absent -> JSON null).
sha() {
  if [[ -f "$1" ]]; then
    sha256sum -- "$1" | awk '{print $1}'
  fi
}

# First stdout/stderr line of a command; empty (-> JSON null) if unavailable.
firstline() {
  command -v "$1" >/dev/null 2>&1 || return 0
  "$@" 2>&1 | head -n1 || true
}

# --- gather ------------------------------------------------------------------

GENERATED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
HEAD_SHA="$(git rev-parse HEAD)"
BRANCH="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || true)"
PORCELAIN="$(git status --porcelain=v1 --ignore-submodules=dirty 2>/dev/null || true)"
SUBMODULES="$(git submodule status --recursive 2>/dev/null || true)"
GITLINK="$(git ls-tree HEAD app/src/main/cpp/third_party/llama.cpp 2>/dev/null || true)"

PATCH_SHA="$(sha patches/llama.cpp/ggml-vulkan-local-build.patch)"
IN_APP_GRADLE="$(sha app/build.gradle.kts)"
IN_CMAKE="$(sha app/src/main/cpp/CMakeLists.txt)"
IN_GRADLE_PROPS="$(sha gradle.properties)"
IN_WRAPPER="$(sha gradle/wrapper/gradle-wrapper.properties)"

JAVA_V="$(firstline java -version)"
CMAKE_V="$(firstline cmake --version)"
NINJA_V="$(firstline ninja --version)"
GRADLE_WRAPPER=""
if [[ -f gradle/wrapper/gradle-wrapper.properties ]]; then
  GRADLE_WRAPPER="$(grep -E '^[[:space:]]*distributionUrl=' gradle/wrapper/gradle-wrapper.properties \
    | head -n1 | sed -E 's/^[^=]*=[[:space:]]*//')"
fi

NOTES="Generated by scripts/inference/capture-baseline.sh (do not hand-edit). Source-derived baseline only: model, device, driver and measured/benchmark provenance are intentionally absent until an on-device run; add a separate run record under research/inference/results/ for any measurement."

export RC_SCHEMA_VERSION="1"
export RC_GENERATED_AT="$GENERATED_AT"
export RC_HEAD="$HEAD_SHA"
export RC_BRANCH="$BRANCH"
export RC_PORCELAIN="$PORCELAIN"
export RC_SUBMODULES="$SUBMODULES"
export RC_GITLINK="$GITLINK"
export RC_PATCH_SHA="$PATCH_SHA"
export RC_JAVA="$JAVA_V"
export RC_CMAKE="$CMAKE_V"
export RC_NINJA="$NINJA_V"
export RC_GRADLE_WRAPPER="$GRADLE_WRAPPER"
export RC_IN_APP_GRADLE="$IN_APP_GRADLE"
export RC_IN_CMAKE="$IN_CMAKE"
export RC_IN_GRADLE_PROPS="$IN_GRADLE_PROPS"
export RC_IN_WRAPPER="$IN_WRAPPER"
export RC_NOTES="$NOTES"

# --- emit (python3 when available; pure-bash fallback otherwise) -------------

emit_python() {
  python3 - <<'PY'
import json, os

def val(name):
    v = os.environ.get(name, "")
    return v if v != "" else None

def lines(name):
    v = os.environ.get(name, "")
    return v.splitlines() if v != "" else []

doc = {
    "schemaVersion": int(os.environ["RC_SCHEMA_VERSION"]),
    "generatedAt": os.environ["RC_GENERATED_AT"],
    "git": {
        "head": val("RC_HEAD"),
        "branch": val("RC_BRANCH"),
        "porcelain": lines("RC_PORCELAIN"),
        "submodules": lines("RC_SUBMODULES"),
    },
    "llamaCppGitlink": val("RC_GITLINK"),
    "localPatchSha256": val("RC_PATCH_SHA"),
    "toolchain": {
        "java": val("RC_JAVA"),
        "cmake": val("RC_CMAKE"),
        "ninja": val("RC_NINJA"),
        "gradleWrapper": val("RC_GRADLE_WRAPPER"),
    },
    "buildInputsSha256": {
        "app/build.gradle.kts": val("RC_IN_APP_GRADLE"),
        "app/src/main/cpp/CMakeLists.txt": val("RC_IN_CMAKE"),
        "gradle.properties": val("RC_IN_GRADLE_PROPS"),
        "gradle/wrapper/gradle-wrapper.properties": val("RC_IN_WRAPPER"),
    },
    "notes": os.environ["RC_NOTES"],
}
print(json.dumps(doc, indent=2, sort_keys=False))
PY
}

json_escape() {
  local s="$1"
  s="${s//\\/\\\\}"
  s="${s//\"/\\\"}"
  s="${s//$'\n'/\\n}"
  s="${s//$'\r'/\\r}"
  s="${s//$'\t'/\\t}"
  printf '%s' "$s"
}

jstr() {
  if [[ -z "${1:-}" ]]; then printf 'null'; else printf '"%s"' "$(json_escape "$1")"; fi
}

jarr() {
  local input="${1:-}"
  if [[ -z "$input" ]]; then printf '[]'; return; fi
  local out="[" sep="" line
  while IFS= read -r line; do
    out+="$sep$(jstr "$line")"
    sep=$',\n'
  done <<< "$input"
  printf '%s]' "$out"
}

emit_bash() {
  printf '{\n'
  printf '  "schemaVersion": %s,\n' "$RC_SCHEMA_VERSION"
  printf '  "generatedAt": %s,\n' "$(jstr "$RC_GENERATED_AT")"
  printf '  "git": {\n'
  printf '    "head": %s,\n' "$(jstr "$RC_HEAD")"
  printf '    "branch": %s,\n' "$(jstr "$RC_BRANCH")"
  printf '    "porcelain": %s,\n' "$(jarr "$RC_PORCELAIN")"
  printf '    "submodules": %s\n' "$(jarr "$RC_SUBMODULES")"
  printf '  },\n'
  printf '  "llamaCppGitlink": %s,\n' "$(jstr "$RC_GITLINK")"
  printf '  "localPatchSha256": %s,\n' "$(jstr "$RC_PATCH_SHA")"
  printf '  "toolchain": {\n'
  printf '    "java": %s,\n' "$(jstr "$RC_JAVA")"
  printf '    "cmake": %s,\n' "$(jstr "$RC_CMAKE")"
  printf '    "ninja": %s,\n' "$(jstr "$RC_NINJA")"
  printf '    "gradleWrapper": %s\n' "$(jstr "$RC_GRADLE_WRAPPER")"
  printf '  },\n'
  printf '  "buildInputsSha256": {\n'
  printf '    "app/build.gradle.kts": %s,\n' "$(jstr "$RC_IN_APP_GRADLE")"
  printf '    "app/src/main/cpp/CMakeLists.txt": %s,\n' "$(jstr "$RC_IN_CMAKE")"
  printf '    "gradle.properties": %s,\n' "$(jstr "$RC_IN_GRADLE_PROPS")"
  printf '    "gradle/wrapper/gradle-wrapper.properties": %s\n' "$(jstr "$RC_IN_WRAPPER")"
  printf '  },\n'
  printf '  "notes": %s\n' "$(jstr "$RC_NOTES")"
  printf '}\n'
}

emit() {
  if command -v python3 >/dev/null 2>&1; then
    emit_python
  else
    emit_bash
  fi
}

# --- output ------------------------------------------------------------------

if [[ "$APPLY" -eq 1 ]]; then
  out_dir="$(dirname -- "$OUT")"
  if [[ ! -d "$out_dir" ]]; then
    echo "capture-baseline: refusing to create directory '$out_dir' (only --out may be written)" >&2
    exit 3
  fi
  tmp="$(mktemp "${TMPDIR:-/tmp}/baseline.lock.XXXXXX")"
  trap 'rm -f "$tmp"' EXIT
  emit >"$tmp"
  chmod 0644 -- "$tmp"
  mv -- "$tmp" "$OUT"
  trap - EXIT
  echo "capture-baseline: wrote $OUT" >&2
else
  emit
fi
